public class Hashmap123 {
    public void method()
    {
 Map < String, String > hm = new Map < String, String >();
hm.put('key1', 'Value1');
hm.put('key2', 'Value2');
hm.put('key3', 'Value3');
hm.put('key4', 'Value4');
hm.put('key5', 'value5');
hm.put('key6', 'value6');
hm.put('key7', 'value7');
hm.put('key8', 'value8');
hm.put('key9', 'value9');
hm.put('key10', 'value10');
    System.debug(hm);
//for(String ss:hm.keyset())
//system.debug(ss);
       // for(String ss1:hm.values())
          //  System.debug(ss1);
    } 
}