public class StringMethods {
    String s1='dextara';
         String s2='DeXtarA';
    public void methods(){
           System.debug(s1.charAt(3));
        System.debug(s1.toLowerCase());
        System.debug(s2.toLowerCase());
        System.debug(s1.toUpperCase());
        System.debug(s2.splitByCharacterTypeCamelCase());
        System.debug(s1.length());
           System.debug(s2.length());
                        System.debug(s2.endsWith('A'));
                        System.debug(s1.compareTo(s2));
        
    }
                        

}