public class WhileHashMap {
    public void dpl()
    {
Map < String, String > hm12 = new Map < String, String >();
hm12.put('key1', 'Value1');
hm12.put('key2', 'Value2');
hm12.put('key3', 'Value3');
hm12.put('key4', 'Value4');
hm12.put('key5', 'value5');
hm12.put('key6', 'value6');
hm12.put('key7', 'value7');
hm12.put('key8', 'value8');
hm12.put('key9', 'value9');
hm12.put('key10', 'value10');


    }   
}